server:
  port: 8762

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    user-service:
      path: /user/login
      service-id: user-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

    gallery-service:
      path: /gallery/**
      service-id: gallery-service
